### ISSUE TITLE
.subtags('aa') throws error

### ISSUE THREAD

**Issue by MartijnR** [mattcg/language-tags#2] opened 2015-07-09 22:30 UTC
By coincidence I found that, tags.subtag('aa') throws an error:

```
Error: Non-existent subtag 'aa' of type 'language'.
```

I'd expect an empty array as result.

**Comment by mattcg** [comment] 2015-07-09 22:46
Duplicate of #1. This is fixed by the same fix.

**Closed as completed by mattcg** 2015-07-09 22:46 UTC
